AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Description: Infrastructure to host the Cloudfront error page

Parameters:
  CodeSigningConfigArn:
    Type: String
    Description: >
      The ARN of the Code Signing Config to use, provided by the deployment pipeline
    Default: "none"
  PermissionsBoundary:
    Type: String
    Description: >
      The ARN of the permissions boundary to apply to any role created by the template
    Default: "none"
Conditions:
  UseCodeSigning:
    Fn::Not:
      - Fn::Equals:
          - !Ref CodeSigningConfigArn
          - "none"
  UsePermissionsBoundary:
    Fn::Not:
      - Fn::Equals:
          - !Ref PermissionsBoundary
          - "none"
Globals:
  Function:
    CodeSigningConfigArn: !If
      - UseCodeSigning
      - !Ref CodeSigningConfigArn
      - !Ref AWS::NoValue
    PermissionsBoundary: !If
      - UsePermissionsBoundary
      - !Ref PermissionsBoundary
      - !Ref AWS::NoValue

Resources:
  CFErrorPageBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: "Enabled"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Source
          Value: "govuk-one-login/static-error-pages/cloudformation/template"

  StaticSiteInvoke:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt StaticSiteUploadLambdaFunction.Arn
      FunctionName: !Ref StaticSiteUploadLambdaFunction

  StaticSiteUploadLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      #checkov:skip=CKV_AWS_117:vpc not required for this simple S3 upload
      #checkov:skip=CKV_AWS_116:dlq not required for this simple S3 upload function
      #checkov:skip=CKV_AWS_173:encryption not required
      #checkov:skip=CKV_AWS_115:concurency setup not required
      CodeUri: uploadErrorPageLambda
      AutoPublishAlias: LatestVersion
      FunctionName: upload-cf-error-page
      Runtime: python3.12
      Layers:
        - !Ref StaticSiteUploadLayer
      Timeout: 5
      Handler: uploadStaticFailover.handler
      PermissionsBoundary:

      Policies:
        - S3WritePolicy:
            BucketName: !Ref CFErrorPageBucket
      Environment:
        Variables:
          BucketName: !Ref CFErrorPageBucket

  StaticSiteUploadLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: uploadErrorPageLambda
      CompatibleRuntimes:
        - python3.12
    Metadata:
      BuildMethod: makefile